from dotenv import load_dotenv
load_dotenv()

import os
import sqlite3

# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
from langchain.agents import AgentType
from langchain_openai import ChatOpenAI
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent

llm = ChatOpenAI(
    api_key=os.environ["HUGGINGFACEHUB_API_TOKEN"],
    base_url="https://router.huggingface.co/v1",
    model="Qwen/Qwen3.5-397B-A17B:novita",
    temperature=0.0,
)

db_path = os.path.join(os.path.dirname(__file__), "chinook.db")
conn = sqlite3.connect(db_path)
cur = conn.cursor()
cur.execute(
    """
    CREATE TABLE IF NOT EXISTS Album (
        AlbumId INTEGER PRIMARY KEY,
        Title TEXT NOT NULL
    )
    """
)
cur.execute("SELECT COUNT(*) FROM Album")
if cur.fetchone()[0] == 0:
    cur.executemany(
        "INSERT INTO Album (AlbumId, Title) VALUES (?, ?)",
        [(1, "For Those About To Rock"), (2, "Balls to the Wall"), (3, "Restless and Wild")],
    )
conn.commit()
conn.close()

sqlite_uri = f"sqlite:///{db_path}"
db = SQLDatabase.from_uri(sqlite_uri)

agent_executor = create_sql_agent(llm=llm, db=db, verbose=True, handle_parsing_errors=True, agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION)

# Direct SQL invoke
print(db.run("SELECT COUNT(*) AS album_count FROM Album;"))

# Natural-language invoke through agent
print(agent_executor.invoke("How many albums are there in the database?"))
